### ISSUE TITLE
Component: Button to PF4

### ISSUE THREAD

**Issue by jenny-s51** [quipucords/quipucords-ui#134]
## Feature description
Convert PF3 Buttons to PF4 Buttons for the following:

- [x] #136 
- [x] #142
- [x] #142 

### Related issue
[DISCOVERY-149](https://issues.redhat.com/browse/DISCOVERY-149)
related #97

**Comment by cdcabrera** [comment]
As of 20220819 we need to confirm the remaining buttons are located around our table refactors
