### ISSUE TITLE
Database lock error in QPC results in large, unpleasant error message in UI

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords-ui#16]
@dsesami commented on [Fri Aug 10 2018](https://github.com/quipucords/quipucords/issues/1402)

## Specify type:
- Enchancement

### Priority:
- Medium
___

## Description:
The database locking issue (documented in quipucords/quipucords/issues/1275) results in an alert/toast that appears on the page showing the entire error. The following screenshot shows this error after attempting to delete a source.

![screenshot from 2018-08-10 11-26-02](https://user-images.githubusercontent.com/19942822/43966663-7bce4f86-9c90-11e8-90e1-ae4d3ccc1c87.png)

___

## Acceptance Criteria:

- [ ] Verify that if the database lock error occurs, a more readable error is presented.

___

### Version Information:
Quipucords, master, latest (0.0.43)

### Steps to reproduce:
See quipucords/quipucords/issues/1275. Typically, using automation to delete sources quickly in succession can trigger the database lock.

---

@cdcabrera commented on [Sat Aug 11 2018](https://github.com/quipucords/quipucords/issues/1402#issuecomment-412260261)

Declaring this as a bug with weight leads to the conclusion there is a recommended UI solution. 

**Statements that help round out this issue declaration are**
- we acknowledge this isn't really a UI issue, but rather an API/server level error response formatting problem
- we acknowledge that customizing the UI around specific API/server level issues can lead to unexpected display results and may need to be applied across all error response messages to provide consistency for display... this feels slightly ironic
- we acknowledge there may need to be some form of API to UI, or vice versa, response/endpoint around the database lock

**Questions that help round out this issue declaration are**
- what http status can be displayed, if any, to relate this problem?
- what length of characters, if any, are the minimum for truncating so that the UI end user still gains an understanding of the problem?
- do we need some form of API to UI, or vice versa, interaction so the UI is aware of the database lock... or can we avoid being needlessly complex?
- do we simply need to display a generic "error" message? if so, what should it display?

@kdelee @dsesami @kholdaway @bclarhk 

---

@kholdaway commented on [Sat Aug 11 2018](https://github.com/quipucords/quipucords/issues/1402#issuecomment-412273421)

This isn’t a UI bug. We have a bug open for this dblock already. 

---

@dsesami commented on [Mon Aug 13 2018](https://github.com/quipucords/quipucords/issues/1402#issuecomment-412511355)

Changed to an enhancement instead of a bug based on above commentary @kholdaway @cdcabrera.

Is there a better label for this besides UI/UX, or should I take that off completely? My main issue is that I think showing stack traces on the front end isn't the best, and that it should be confined to logs. We could specify a 500-type internal server error and say to refer to the logs somehow.

---

@kholdaway commented on [Mon Aug 13 2018](https://github.com/quipucords/quipucords/issues/1402#issuecomment-412524195)

I guess it could be an enhancement for general server 500 handling. Not just DB lock.

---

@elyezer commented on [Mon Dec 03 2018](https://github.com/quipucords/quipucords/issues/1402#issuecomment-443782686)

@kholdaway @cdcabrera should we close this since we are now using postgres and the DB lock won't happen or update so this can be used to improved 500 errors?

---

@cdcabrera commented on [Mon Dec 03 2018](https://github.com/quipucords/quipucords/issues/1402#issuecomment-443816088)

I like the idea of working it towards 500 level errors instead.  

Can do something similar to this project
- https://github.com/cloudigrade/frontigrade

and the code to implement
- https://github.com/cloudigrade/frontigrade/blob/master/src/redux/middleware/statusMiddleware.js
- https://github.com/cloudigrade/frontigrade/blob/master/src/common/helpers.js#L91-L136
- https://github.com/cloudigrade/frontigrade/blob/master/src/redux/reducers/toastNotificationsReducers.js#L60-L78

---

@elyezer commented on [Mon Dec 03 2018](https://github.com/quipucords/quipucords/issues/1402#issuecomment-443816612)

@cdcabrera I like that :+1:. So I will leave this open then

**Comment by cdcabrera** [comment]
As of 20190312 - Adding a global filter for errors within the app appears to require a rewrite of how we handle Redux actions and service calls

**Comment by cdcabrera** [comment]
As of 20190312 shutting this down in favor of #24
