### ISSUE TITLE
Scan status is never updated on the UI when completed

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords-ui#17]
@elyezer commented on [Thu Nov 22 2018](https://github.com/quipucords/quipucords/issues/1711)

## Bug Description:
Starting a scan and checking its status on the Scans page will show that the `Job is pending.` but this status never updates unless the page is refreshed.

### Expected behavior:
The scan status should get updated when the scan job is completed.

### Actual behavior:
The `Job is pending` status is never updated.

### Steps to reproduce:
1) Create and start a scan
2) Navigate to the `Scans` page and check its status. It should be `Job is pending`.
3) Watch the quipucords server log until the started scan job is completed.
4) Come back on the UI and it should not be updated, saying that the scan was completed. (It will update the status if the page is refreshed).
___

## Acceptance Criteria:

- [x] Verify that the scan status will be updated on the Scans page.

___

### Version Information:
1aa29c2175dd34e4f85b9e541b0479b0a08add88

### Environment information:

This should happen with any scan.

---

@cdcabrera commented on [Tue Feb 05 2019](https://github.com/quipucords/quipucords/issues/1711#issuecomment-460685185)

This request is more related to a polling feature, something not currently implemented. Looking at working this into the parallel issue of #1822

**Comment by cdcabrera** [comment]
As of 20190529 we implemented polling in the GUI based on a scan either being `pending` or `running` this should meet the requirements associated with this issue.

See PR #48

**Comment by elyezer** [comment]
@himmAllRight it seems we can add/improve the UI tests related to this now.
