### ISSUE TITLE
User Story: Update framework and syntax

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords-ui#18]
@cdcabrera commented on [Mon Jan 28 2019](https://github.com/quipucords/quipucords/issues/1791)

### Is your feature request related to a problem?
React framework and general optimization updates (Or making the GUI devs lives easier by making this repository reflect updated knowledge for how we structure code bases). 

Currently the GUI is fixed on a specific version of React. In order to upgrade various syntax and React life cycle methods need to be altered. 

### Describe the solution you'd like
Behind the scenes GUI code updates:
- Update services to remove class based structure
- Update redux structure in an effort to simplify state
  - evaluate selectors 
  - update toolbar filters
- Update legacy React life cycle methods within components
  - this should bring with it a reduction in component complexity
- Expand unit tests and coverage to promote GUI code stability, and relax the need to always require another UI dev resource in addition to the QE team reviews
  - expose coverage and build aspects on the GUI Readme, aim for a minimum of 70% + coverage
___

## Acceptance Criteria:
- [x] Services should no longer contain class based structure
  - separate helper functions into `common/helpers`
- Clean up Redux structure, should include 
  - [x] removing unused types, actions, reducer checks
  - ~clean up lodash usage within redux, evaluate `lodash-es`~ until we can move to a newer version of the react scripts going to delay this
  - [x] unit tests expanded
- [x] Verify that users see no discernible negative difference within the GUI. increases in response and render time may be a positive outcome
- [x] Verify that GUI unit tests are expanded and achieve a minimum of 70% coverage
  - [x] Component testing 
  - [x] State / Redux testing
  - [x] Services testing
- [x] Verify that legacy React life cycle methods have been removed... searching in the code base for `componentWillReceiveProps` should return 0 results 

## Related issues
#1520

**Comment by cdcabrera** [comment]
As of 20190529... 

There is one last grouping of components that retain the legacy lifecycle methods... Credentials components. We may end up doing a quick conversion then iterate on it instead of our normal in-depth conversion. This would let us close this ongoing issue down.

**Comment by cdcabrera** [comment]
As of 20190703...

There is still one last grouping of components that retain the legacy lifecycle methods... Credentials components.

**Comment by cdcabrera** [comment]
Marking this one finally resolved as of 20220628 as part of the prep for the segue to patternfly 4
- updated to react 17
   - one or two legacy lifecycles are still in there, but they should be removed as part of the pf4 refactors come through
- npm packages updated
- local build flipped from github actions instead of travis
