### ISSUE TITLE
User Story: Sources, Add Creation Options

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords-ui#19]
@cdcabrera commented on [Mon Feb 04 2019](https://github.com/quipucords/quipucords/issues/1821)

## Feature description:

As a QPC user, I want to use the UI to create my sources but it lacks several options present in the CLI.  The QPC source creation dialogue should include inputs for:

- Create a source with --ssl-protocol
- Create a source with --disable-ssl
- Create a source with --use-paramiko

### NOTES:
--ssl-protocol is mutually exclusive with --disable-ssl
--ssl-protocol accepts valid inputs of {SSLv23,TLSv1,TLSv1_1,TLSv1_2}
--use-paramiko is mutually exclusive with --disable-ssl
--use-paramiko is mutually exclusive with --ssl-protocol 

___

## Acceptance Criteria:

- [x] Verify that users can create a source with --ssl-protocol
- [x] Verify that users can create a source with --disable-ssl
- [x] Verify that users can create a source with --use-paramiko
- [x] Verify that validation resolves issue https://github.com/quipucords/quipucords/issues/1783 host validation

## Related Issues/Stories
https://github.com/quipucords/quipucords/issues/1783

---

@bclarhk commented on [Thu Feb 07 2019](https://github.com/quipucords/quipucords/issues/1821#issuecomment-461547104)

PSA: Capitalization has been changed to sentence style
![add network range](https://user-images.githubusercontent.com/32572198/52435080-dec3f000-2ade-11e9-95ce-682499315356.png)
![add satellite](https://user-images.githubusercontent.com/32572198/52435081-dec3f000-2ade-11e9-9813-b6efa8bb1607.png)
![add vcenter](https://user-images.githubusercontent.com/32572198/52435082-df5c8680-2ade-11e9-9394-e477151726bf.png)

---

@cdcabrera commented on [Fri Mar 01 2019](https://github.com/quipucords/quipucords/issues/1821#issuecomment-468703410)

Primary resolution merged as of 20190228, temporarily leaving this open due to #1840

**Comment by cdcabrera** [comment]
A of 20190312 considered resolved
