### ISSUE TITLE
Add Source Wizard, add 1 or more vcenter or satellite sources

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords-ui#22]
@mdvickst commented on [Wed Feb 13 2019](https://github.com/quipucords/quipucords/issues/1840)

## Feature description:
It would be very helpful to have a wizard that prompts customers to add 1 or more network sources, 1 or more vcenters sources and 1 or more satellite sources. This would make sure that customers add all sources if they have them and not just rely on 1 or 2 sources. 

I think this is more targeted at the GUI but I could see a CLI prompt being helpful as well. 

### Is your feature request related to a problem?
Please describe.  A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### Describe the solution you'd like

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

## Additional context

---

@cdcabrera commented on [Thu Feb 28 2019](https://github.com/quipucords/quipucords/issues/1840#issuecomment-468428222)

This issue probably should have been linked to issue #1821 

@bclarhk thoughts?

---

@kholdaway commented on [Tue Mar 12 2019](https://github.com/quipucords/quipucords/issues/1840#issuecomment-472043385)

Issue moved to [quipucords/quipucords-ui #21](https://github.com/quipucords/quipucords-ui/issues/21) via [**ZenHub**](https://www.zenhub.com/)

**Comment by cdcabrera** [comment]
This should be grouped with #14 and #20 as part of an ongoing source additions improvement
