### ISSUE TITLE
Content services copy integration

### ISSUE THREAD

**Issue by cdcabrera** [quipucords/quipucords-ui#38]
## Feature description
As a developer it would be helpful to be integrated with a documentation or copy based repository so that copy string changes can be made independent of the UI code.

### Describe the solution you'd like
- Option 1: NPM build package reference to a copy repository. Updated strings get checked in to the project manually.
- Option 2: Full CI integration of the NPM build package. Jenkins would run an additional step where the appropriate copy build script would generate the copy strings. This process would possibly require a baseline or fallback set of strings.
## Acceptance Criteria
- [x] Verify the strings currently (before this update) within the copy repo are being used in ui repo.
- [x] Verify README or CONTRIBUTION in the UI and copy repos have been updated to explain this process

___

## Additional context

- Copy strings would be held with JSON resource. The resource could be either loaded through an Ajax request (local files with the ability to expand to an external service in the future), or created as an import module within the app. 
  - This repo uses the Ajax way of handling strings, https://gitlab.com/cloudigrade/frontigrade/issues/90
- Changes to UI would involve adding keys/IDs and implementing a i18n package

**Comment by cdcabrera** [comment]
Baseline string placement ideas
- Deep scan tooltip, scan dialog/modal
- Credential, `View Credential` hover tooltip

Directory placement
- use `dist/ea_out`

**Comment by cdcabrera** [comment]
As of 20190703...

Quipudocs NPM structure has stabilized, and is ready for NPM consumption.

**Comment by jlprevatt** [comment]
As part of this issue, we should consider how we are going to add access to the documentation from the ? menu in the GUI. Such as...

- Two different options (and decide on labels) for install and user documents

- A single "Documentation" or "Help" or whatever menu option with the install and user labels as suboptions
