### ISSUE TITLE
EA copy changes to splash page

### ISSUE THREAD

**Issue by jlprevatt** [quipucords/quipucords-ui#40]
Requesting a few tweaks to splash page embedded assistance inline text, since that issue (#6) wrapped up while I was out for surgery. Comments based on attached final screens in https://github.com/quipucords/quipucords-ui/pull/27.

1. Tighten up product intro text to read: "Welcome to product discovery! This inspection and reporting tool is designed..." _(replacing "Welcome to product discovery! This is an inspection and reporting tool. It is designed...")_

1. Informational message for logged out state, avoid fancy verb tenses and stick with the simple ones: "You are logged out. ...." _(replacing "You have been logged out.")_

**Comment by cdcabrera** [comment]
@jlprevatt
