### ISSUE TITLE
Add output checks to UI builds

### ISSUE THREAD

**Issue by himmAllRight** [quipucords/quipucords-ui#7]
## Feature description
Put some system in place to check that the required files generated from the UI build properly exist to be bundled and passed to the quipucords build.

### Is your feature request related to a problem?
It was a suggestion made in PR #3 

### Describe the solution you'd like
After the UI is build, run something that can verify the required files were generated for the artifact package being passed to the quipucords build job.
___

**Comment by cdcabrera** [comment]
As of 20190312 merged and approved
