### ISSUE TITLE
App component: Authentication to PF4

### ISSUE THREAD

**Issue by jenny-s51** [quipucords/quipucords-ui#92]
## Acceptance criteria
- Convert `authentication.js` to use updated PF4 components. Towards #91 -- includes the Alert component.

## Assumptions and questions
- avoid the urge to completely rewrite this, reserve for a round 2
- attempt to convert the strings towards the `translate` method. example can be found here - https://github.com/cdcabrera/quipucords-ui/commit/b3c8eaa48d844f46ca6f6dd44c9cd0c84f5dcc52

**Comment by cdcabrera** [comment]
@jenny-s51 here's the base work I had started a few days ago on Authentication... I stopped around the Alert component, https://github.com/cdcabrera/quipucords-ui/commit/b3c8eaa48d844f46ca6f6dd44c9cd0c84f5dcc52
