### ISSUE TITLE
Translation: Convert in-app strings to use `translate` method

### ISSUE THREAD

**Issue by cdcabrera** [quipucords/quipucords-ui#93]
## Acceptance criteria
- search and replace instances of standalone strings with the `translate` method

## Assumptions and questions
- Convert in-app strings to use the `translate` method exported from the `i18n` component
-  apply strings to the `public/locales/en.json` file
- **some conversions may be easier to handle while updating the component itself**

**Comment by cdcabrera** [comment]
@jenny-s51 I would prefer clean up tasks be handled last. there's a high probability they will cause merge and rebase conflicts if handled in the regular flow

**Comment by jenny-s51** [comment]
Sounds like a good plan @cdcabrera ! I didn't realize the clean up label indicated things we want to handle last. No worries, in that case I will pivot to another issue!

**Comment by cdcabrera** [comment]
As of 20220817 recommending we attempt converting some string conversions to familiarize ourselves with i18next string context and removing string display logic

**Comment by cdcabrera** [comment]
As of 20221005 the remaining files contain strings not within the locale files
- `./src/components/router/routerConstants` - includes links displayed in view left nav
- `./src/components/createCredentialDialog/createCredentialDialog.js` - this form needs to be refactored to align to other forms, avoiding string updates since the refactor has the potential to reduce display strings

**Comment by cdcabrera** [comment]
As of 20221103 the remaining known files that contain strings not within locale 
- login/out pages
- `./src/components/router/routerConstants`

There may be additional one-off strings elsewhere

**Comment by cdcabrera** [comment]
We're going to mark this issue complete as an aspect of the PF4 refactors and follow it up with a specific "clean up remaining strings" tech debt, see #191
